{
 "title": "Lodestar Holesky",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Node summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(time() - lodestar_genesis_time{package=\"lodestar-prater.dnp.dappnode.eth\"}) / 12",
     "legendFormat": "clock slot"
    },
    {
     "expr": "beacon_head_slot{package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "head slot"
    },
    {
     "expr": "changes(process_start_time_seconds{package=\"lodestar-prater.dnp.dappnode.eth\"}[5m])",
     "legendFormat": "process restart"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(lodestar_peers_by_direction_count{package=\"lodestar-prater.dnp.dappnode.eth\"})"
    }
   ]
  },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_head_slot{package=\"lodestar-prater.dnp.dappnode.eth\"}"
    }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{package=\"lodestar-prater.dnp.dappnode.eth\"}"
    }
   ]
  },
  {
   "title": "Validators connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_monitor_validators{package=\"lodestar-prater.dnp.dappnode.eth\"}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"} [1m])"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"}"
    }
   ]
  },
  {
   "title": "Uptime since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"}*1000"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_sync_status{package=\"lodestar-prater.dnp.dappnode.eth\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_version{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Lodestar version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_version{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_peers_by_direction_count{package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "lodestar_gossip_peer_score_by_threshold_count{threshold=\"mesh\", package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "with_gossip_mesh_score"
    }
   ]
  },
  {
   "title": "Validators prev epoch miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_attester_miss_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_attester_hit_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_attester_miss_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n) > 0",
     "legendFormat": "attester"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n) > 0",
     "legendFormat": "target"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval]))\n) > 0",
     "legendFormat": "head"
    },
    {
     "expr": "1 - avg(validator_monitor_prev_epoch_on_chain_attester_correct_head_total{package=\"lodestar-prater.dnp.dappnode.eth\"})",
     "legendFormat": "wrong_head_ratio"
    }
   ]
  },
  {
   "title": "Mesh peers on core topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(lodestar_gossip_mesh_peers_by_type_count{package=\"lodestar-prater.dnp.dappnode.eth\"}) by (instance)",
     "legendFormat": "core_topics_avg"
    },
    {
     "expr": "avg(lodestar_gossip_mesh_peers_by_beacon_attestation_subnet_count{package=\"lodestar-prater.dnp.dappnode.eth\"} > 0) by (instance)",
     "legendFormat": "attestation_subnets_avg"
    }
   ]
  },
  {
   "title": "balance delta prev epoch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(\n  delta(validator_monitor_prev_epoch_on_chain_balance_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[32m])\n)",
     "legendFormat": "balance_delta"
    },
    {
     "expr": "avg(\n  delta(validator_monitor_prev_epoch_on_chain_balance{package=\"lodestar-prater.dnp.dappnode.eth\"}[32m])\n)",
     "legendFormat": "balance_delta_new"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_peers_by_client_count{package=\"lodestar-prater.dnp.dappnode.eth\"}",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Usage rate (time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_find_head_seconds_sum{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "fork_choice_find_head"
    },
    {
     "expr": "rate(lodestar_block_processor_queue_job_time_seconds_sum{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "block_processor"
    },
    {
     "expr": "rate(lodestar_stfn_epoch_transition_seconds_sum{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "stfn_epoch"
    },
    {
     "expr": "rate(lodestar_stfn_process_block_seconds_sum{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "stfn_block"
    },
    {
     "expr": "sum(rate(nodejs_gc_duration_seconds_sum{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"} [$rate_interval])) by (instance)",
     "legendFormat": "gc_duration_sum"
    },
    {
     "expr": "sum(rate(nodejs_gc_pause_seconds_total{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"} [$rate_interval])) by (instance)",
     "legendFormat": "gc_pause_sum"
    },
    {
     "expr": "sum(rate(lodestar_bls_thread_pool_time_seconds_sum{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])) by (instance)",
     "legendFormat": "bls_thread_pool_sum"
    }
   ]
  },
  {
   "title": "Roundtrip request times - I/O lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_sum{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])\n/\nrate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_count{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "reqresp_outgoing_roundtrip"
    },
    {
     "expr": "rate(lodestar_eth1_http_client_request_time_seconds_sum{routeId=\"getBlockNumber\", package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])\n/\nrate(lodestar_eth1_http_client_request_time_seconds_count{routeId=\"getBlockNumber\", package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "eth1_getBlockNumber_roundtrip"
    },
    {
     "expr": "avg_over_time( scrape_duration_seconds{service=\"beacon-chain.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"} [$rate_interval])",
     "legendFormat": "prometheus_beacon_scrape_roundtrip"
    },
    {
     "expr": "avg_over_time( scrape_duration_seconds{service=\"validator.lodestar-prater.dappnode\", package=\"lodestar-prater.dnp.dappnode.eth\"} [$rate_interval])",
     "legendFormat": "prometheus_validator_scrape_roundtrip"
    },
    {
     "expr": "rate(vc_rest_api_client_request_time_seconds_sum{routeId=\"produceAttestationData\", package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])\n/\nrate(vc_rest_api_client_request_time_seconds_count{routeId=\"produceAttestationData\", package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
     "legendFormat": "rest_produceAttestation_roundtrip"
    }
   ]
  },
  {
   "title": "Network status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "head slot",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_head_slot{package=\"lodestar-prater.dnp.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "finalized epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_finalized_epoch{package=\"lodestar-prater.dnp.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "previous justified epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_previous_justified_epoch{package=\"lodestar-prater.dnp.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "current justified epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_current_justified_epoch{package=\"lodestar-prater.dnp.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "current active validators",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_current_validators{status=\"active\", package=\"lodestar-prater.dnp.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "processed deposits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_processed_deposits_total{package=\"lodestar-prater.dnp.dappnode.eth\"}"
      }
     ]
    },
    {
     "title": "Reorgs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "delta(beacon_fork_choice_reorg_total{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])"
      }
     ]
    },
    {
     "title": "Reorgs depth",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "rate(beacon_fork_choice_reorg_distance_bucket{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Block parent distance (except 1)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "12*rate(beacon_imported_block_parent_distance_bucket{package=\"lodestar-prater.dnp.dappnode.eth\"}[$rate_interval])-1",
       "legendFormat": "{{le}}"
      }
     ]
    },
    { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 } }
   ]
  },
  {
   "title": "Node status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clock drift",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(time() - lodestar_genesis_time{package=\"lodestar-prater.dnp.dappnode.eth\"}) / 12 - lodestar_clock_slot{package=\"lodestar-prater.dnp.dappnode.eth\"}",
       "legendFormat": "clock drift"
      }
     ]
    },
    {
     "title": "Sync status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lodestar_sync_status{package=\"lodestar-prater.dnp.dappnode.eth\"}",
       "legendFormat": "status"
      }
     ]
    },
    {
     "title": "head drift",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lodestar_clock_slot{package=\"lodestar-prater.dnp.dappnode.eth\"} - beacon_head_slot{package=\"lodestar-prater.dnp.dappnode.eth\"}",
       "legendFormat": "clock drift"
      }
     ]
    },
    {
     "title": "-",
     "type": "text",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "lodestar_sync_status{package=\"lodestar-prater.dnp.dappnode.eth\"}",
       "legendFormat": "status"
      }
     ]
    }
   ]
  }
 ]
}